### ISSUE TITLE
problem with tar on pypi

### ISSUE THREAD

**Issue by dmichel76** [iknowledge-io/geolocation-python#18]
Hi,

I just installed your package from pypi (I had to download the tar rather than using pip due to using a proxy, and install it manually by running python setup.py install)... it seemed to install fine but fails when running the example codes as it fails to find the distance_matrix module...

... That's when I realised that the pypi tar does not actually contains the distance_matrix module nor the geocode folder, only the top level files are there.

Is this me or there is an problem here when the tar was build?

**Comment by dmichel76** [comment]
I just tried to install the zip from here... same thing, cannot find the distance_matrix module. Checking my /usr/local/lib/python2.7/dist-packages/geolocation, I don't see the distance_matrix module in there...

Problem with the setup.py ?? or am I doing something wrong here?

**Comment by slawek87** [comment]
fixed. Now You have to reinstall it.

Yeah.. you have right. It was a problem with setup.py.

Thx for reporting!:)

**Comment by dmichel76** [comment]
Great, just tried it and it's all fine now.
